function imgLP = logpolar(img, sampleGrid)
%% imgLP = logpolar(img, sampleGrid)
% Log-Polar transformation frame
% Inputs:   img             source image in Cartisian coordinates% 
%           sampleGrid      sample grid of the Log-Polar coordinates to 
%                           interpolation in Cartisian coordinates,
%                           generated by function 'lptform.m', see
%                           'lptform.m' for detail
% 
% Outputs:  imgLP           output image in Log-Polar coordinates
% 
% Copyright: njustmxn@163.com
% Revised:   2016.1.11
% Revised:   2016.4.28

%%
if strcmp(class(img), 'uint8')
    img = im2double(img);
end
imgLP = interp2(img, sampleGrid{1}, sampleGrid{2}, 'linear');

% any pixel outside warp, pad with 0
% c = size(sampleGrid{1}, 2);
% r = size(sampleGrid{2}, 1);
% mask= (sampleGrid{1} > c) | (sampleGrid{1} < 1) | ...
%         (sampleGrid{2} > r) | (sampleGrid{2} < 1);
% any pixel outside warp will be NaN, fix it to 0
mask = isnan(imgLP);
imgLP(mask)=0;
end